config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :transactions
  resources :accounts
  resources :users
  resources :sessions

  root 'users#new'
 
  post '/signin' => 'sessions#create', :as => 'signin'
  get '/signup' => 'users#new', :as => 'signup'
  get '/signout' => 'sessions#destroy', :as => 'signout'

  get '/home' => 'home#index', :as => 'home'
  get '/account/:account_id/transactions' => 'transactions#index', :as => 'account_transactions'
  put '/transfer' => 'transactions#transfer', :as => 'transfer_transactions'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :accounts
  has_many :transactions

  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :logged_in?, :except => [:destroy]
  before_filter :new_user?, :except => [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Signup Successfull!"
      redirect_to root_url
    else
      flash[:error] = "Error Signing Up"
      render 'users/new'
    end
  end

  def destroy
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
  
  def new_user?
    if current_user.present?
      redirect_to home_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.haml
#user-forms
  #signin
    = simple_form_for :session, {:url => signin_path} do |f|
      = f.input :email, :class => 'textfield', :input_html => {:size => 20}
      = f.input :password, :as => :password
      .line-separator
      = f.button :submit, 'SignIn'
    %label.membership
      %a{:onclick => 'showSignup()'} Not yet a Member?
  #signup
    = simple_form_for @user do |f|
      = f.input :first_name, :input_html => {:size => 20}
      = f.input :last_name, :input_html => {:size => 20}
      = f.input :email, :input_html => {:size => 20}
      = f.input :password, :as => :password
      = f.input :password_confirmation, :as => :password
      .line-separator
      = f.button :submit, 'SignUp'
    %label.membership
      %a{:onclick => 'showSignin()'} Already a Member?

:javascript
  showSignup = function(){
    $('#signup').css('display', 'block'); 
    $('#signin').css('display', 'none');
  }

  showSignin = function(){
    $('#signup').css('display', 'none'); 
    $('#signin').css('display', 'block');
  }