config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :transactions
  resources :accounts
  resources :users
  resources :sessions

  root 'users#new'
 
  post '/signin' => 'sessions#create', :as => 'signin'
  get '/signup' => 'users#new', :as => 'signup'
  get '/signout' => 'sessions#destroy', :as => 'signout'

  get '/home' => 'home#index', :as => 'home'
  get '/account/:account_id/transactions' => 'transactions#index', :as => 'account_transactions'
  put '/transfer' => 'transactions#transfer', :as => 'transfer_transactions'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    if params.include?(:account_id)
      account_id = params[:account_id]
      @transactions = Transaction.where(:account_id => account_id)
    else
      @transactions = Transaction.all
    end

    respond_to do |format|
      format.html
      format.json { render :json =>
          {
            :iTotalRecords => @transactions.count,
            :iTotalDisplayRecords => @transactions.count,
            :aaData =>
                @transactions.map do |transaction|
                  [
                    transaction.dt,
                    link_to(transaction.account.name, account_url(transaction.account.id)),
                    transaction.transaction_type,
                    transaction.amount,
                    transaction.remark
                  ]
                end
          }
        }
      format.js
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      Transaction.transaction do
        begin
          @transaction.save!
          @transaction.account.update_attributes!(:balance => @transaction.account.balance + @transaction.amount)

          format.html { redirect_to root_url, notice: 'Transaction was successfully created.' }
        rescue ActiveRecord::RecordInvalid
          format.html { redirect_to root_url }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
          
          raise ActiveRecord::Rollback
        end
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #PUT
  def transfer
    transfer_params = params[:transfer]
    lender_account = Account.find(transfer_params[:account_id_lender])
    beneficiary_account = Account.find(transfer_params[:account_id_beneficiary])
    amount = transfer_params[:amount]
    remark = transfer_params[:remark]
    date = Date.civil(transfer_params[:"dt(1i)"].to_i, transfer_params[:"dt(2i)"].to_i, transfer_params[:"dt(3i)"].to_i)
  
    respond_to do |format|
      Transaction.transaction do
        begin
          Transaction.create!(:dt => date, :account_id => lender_account.id, :amount => -1*amount.to_i, :remark => remark, :transaction_type => 'dr')
          lender_account.update_attributes!(:balance => lender_account.balance.to_i - amount.to_i)

          Transaction.create!(:dt => date, :account_id => beneficiary_account.id, :amount => amount, :remark => remark, :transaction_type => 'cr')
          beneficiary_account.update_attributes!(:balance => beneficiary_account.balance.to_i + amount.to_i)
         
          format.html { redirect_to root_url, notice: 'Transfer successfully completed'}
        rescue ActiveRecord::RecordInvalid
          format.html { redirect_to root_url }
          raise ActiveRecord::Rollback
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:dt, :account_id, :amount, :remark, :transaction_type)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= simple_form_for @transaction do |f|
  .field
    = f.input :dt, :as => :date, :label => 'Date'
  .field
    = f.input :account_id, :as => :select, :collection => Account.all.collect{|account| [account.name, account.id]}
  .field
    = f.input :amount
  .field
    = f.input :remark
  .field
    = f.input :transaction_type, :collection => Transaction::TYPES
  .line-separator
  .actions
    = f.button :submit

app/views/transactions/_transfer.html.haml
= simple_form_for :transfer, {:url => transfer_transactions_url, :method => 'put', :html => {:id => 'new_transfer'}} do |f|
  .field
    = f.input :dt, :as => :date, :label => 'Date'
  .field
    = f.input :account_id_lender, :label => 'From', :as => :select, :collection => Account.all.collect{|account| [account.name, account.id]}
  .field
    = f.input :account_id_beneficiary, :label => 'Beneficiary', :as => :select, :collection => Account.all.collect{|account| [account.name, account.id]}
  .field
    = f.input :amount, :as => :integer
  .field
    = f.input :remark, :as => :text
  .line-separator
  .actions
    = f.button :submit

app/views/transactions/edit.html.haml
%h1 Editing transaction
= render 'form'
= link_to 'Show', @transaction
|
\#{link_to 'Back', transactions_path}

app/views/transactions/index.html.haml
%table#transactions-container{:data => {:source => "#{params[:account_id].present? ? account_transactions_url : transactions_url}"}}
  %thead
    %tr
      %th Date
      %th Account
      %th Transaction type
      %th Amount
      %th Remark

app/views/transactions/new.html.haml
%h1 New transaction
= render 'form'
= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice
%p
  %strong Dt:
  = @transaction.dt
%p
  %strong Account:
  = @transaction.account_id
%p
  %strong Amount:
  = @transaction.amount
%p
  %strong Remark:
  = @transaction.remark
%p
  %strong Transaction type:
  = @transaction.transaction_type
= link_to 'Edit', edit_transaction_path(@transaction)
|
\#{link_to 'Back', transactions_path}