config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :transactions
  resources :accounts
  resources :users
  resources :sessions

  root 'users#new'
 
  post '/signin' => 'sessions#create', :as => 'signin'
  get '/signup' => 'users#new', :as => 'signup'
  get '/signout' => 'sessions#destroy', :as => 'signout'

  get '/home' => 'home#index', :as => 'home'
  get '/account/:account_id/transactions' => 'transactions#index', :as => 'account_transactions'
  put '/transfer' => 'transactions#transfer', :as => 'transfer_transactions'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transactions

  TYPES = [['SAVINGS', 'savings'], ['CREDIT', 'credit'], ['PF', 'pf'], ['PERSON', 'person']] 

  validates :name, :uniqueness => true, :presence => true
  validates :account_type, :presence => true, :inclusion => {:in => TYPES.map{|o| o[1]}}

  def self.savings
    Account.where(:account_type => ['savings'])
  end

  def self.pf
    Account.where(:account_type => ['pf'])
  end

  def self.credit
    Account.where(:account_type => ['credit'])
  end

  def self.person
    Account.where(:account_type => ['person'])
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    accounts = current_user.accounts

    respond_to do |format|
      format.html
      format.json { render :json => 
          {
            :iTotalRecords => accounts.count,
            :iTotalDisplayRecords => accounts.count,
            :aaData => 
              accounts.map do |account| 
                [
                  link_to(account.name, account_transactions_url(account.id)),
                  account.account_type,
                  account.balance
                ]
              end
           }
        }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to root_url, notice: 'Account was successfully created.' }
      else
        format.html { render root_url }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :account_type, :balance)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
= simple_form_for @account do |f|
  .field
    = f.input :name, :input_html => {:size => 15, :max_length => 25}
  .field
    = f.input :account_type, :label => "Type", :collection => Account::TYPES, :include_blank => false
  .field
    = f.input :balance
  .line-separator
  .actions
    = f.button :submit

app/views/accounts/_index.html.haml
%table#accounts-container{:data => {:source => "#{accounts_url}"}}
  %thead
    %tr
      %th Name
      %th Type
      %th Balance
  %tbody

app/views/accounts/_summary.html.haml
.balance_info
  = 'Savings : '
  = saving_balance
.balance_info
  = 'Credit : '
  = credit_balance
.balance_info
  = 'Person : '
  = in_person_balance
.balance_info
  = 'PF :'
  = pf_balance

app/views/accounts/edit.html.haml
%h1 Editing account
= render 'form'
= link_to 'Show', @account
|
\#{link_to 'Back', accounts_path}

app/views/accounts/index.html.haml
%table#accounts-container{:data => {:source => "#{accounts_url}"}}
  %thead
    %tr
      %th Name
      %th Type
      %th Balance
  %tbody

app/views/accounts/new.html.haml
%h1 New account
= render 'form'
= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @account.name
%p
  %strong Type:
  = @account.account_type
%p
  %strong Balance:
  = @account.balance
= link_to 'Edit', edit_account_path(@account)
|
\#{link_to 'Back', accounts_path}